blog/urls.py
from .views import PostList, PostDetail, deleteBlog, addblog
from django.urls import path
# from blog.views import addBlog
app_name = 'blog'
urlpatterns = [
    path('', PostList.as_view(), name='home'),
    path('delete/<str:slug>/', deleteBlog.as_view(), name='delete_blog'),
    path('add/', addblog, name='add_blog'), # I tried to paste this line in the last url, But it showed me a error and after that I pasted this above ...then it runs
    path('<str:slug>/', PostDetail.as_view(), name='post_detail'),
]

tft1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('login/', include('django.contrib.auth.urls')), # for login authentication # first django checks this path and then come to the custom urls that we have created
    path('login/', include('login.urls')), # for login authentication
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

# The path() function is passed four arguments, 
# two required: route and view, and two optional: kwargs, and name. At this point, it’s worth reviewing what these arguments are for.


#When to use include()
# You should always use include() when you include other URL patterns. 
# admin.site.urls is the only exception to this.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:home') # we have to mention the app name also because we have mentioned that in the url page.
        # this function will be used when we use class based view for add blog in views.py

blog/forms.py
from django import forms
from blog.models import *



class BlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','slug','content','author','status',)
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Title of the Blog'}),
            'slug': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Copy the title with no space and a hyphen in between (slug)'}),
            'author': forms.TextInput(attrs={'class':'form-control', 'value':'', 'type':'hidden',  'id':'id_num', }), # here after , we have to create a small javascript code in add_blog.html ... # here, 'id':'id_num' is created to make the reference to the java script code.
            'content': forms.Textarea(attrs={'class':'form-control', 'placeholder':'''Write Your Content Here.
Note: You Can't Edit Once Created.'''}),
            'status': forms.Select(attrs={'class':'form-control'}),
        }

blog/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from .models import Post
from django.urls import reverse_lazy
from .forms import BlogForm


class PostList(ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'

class PostDetail(DetailView):
    model = Post
    template_name = 'post_detail.html'


#Important:
# Django's home form is returned using the POST method, in which the browser bundles up the form data, encodes it for transmission, sends it to the server, and then receives back its response.
# GET , by contrast, bundles the submitted data into a string, and uses this to compose a URL.
# we use POST and GET while using the function views

# function view
# we have created a particular form for this view in forms.py
def addblog(request): 
    form=BlogForm()
    if request.method=='POST':
        form=BlogForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/blog/')
    context={
        'form':form,
    }
    return render(request,'add_blog.html',context)
    # render responds by HTTP response of context. Here (i.e) forms

class deleteBlog(DeleteView):
    model = Post
    template_name = 'delete_blog.html'
    success_url = reverse_lazy('blog:home')# it asked to provide a success url, so...


# @login_required(login_url = ‘/home’)
# below is the kind of 'FORM' in django, because it takes some input from the user
# class addBlog(CreateView):
#     model = Post
#     template_name = 'add_blog.html'
#     form_class = BlogForm()
#     fields = ('title', 'slug', 'content','author',) # we can give specific fields also...
#     fields = '__all__' # here all takes all the fields from the Post model that we have mentioned above
    # In the above fields we are getting the input from the user
    # fields = ('author',)  using tuples # here author is field of Post model.

blog/templates/add_blog.html
{% extends 'base.html' %}
{% block title %}
Add Post
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<br>
<h1>Add Post</h1>
<!--POST and GET in django-->

<!--POST-->
<!--Django's home form is returned using the POST method, -->
<!--in which the browser bundles up the form data, encodes it for transmission, -->
<!--sends it to the server, and then receives back its response. -->

<!--GET , by contrast, bundles the submitted data into a string, and uses this to compose a URL.-->

<form method="POST">
    {% csrf_token %}
    <div class="container mt-4">
    {{ form.as_p }}
    <button class="btn btn-primary">Post</button>
    </div>
    </form>
    <br>
    <br>
<script>
    var name = "{{ user.id }}";
    document.getElementById('id_num').value = name;
</script>
<!-- The above line is the javascript code. What it do is check the author.id with user.id-->
{% else %}
    You are not allowed :)
{% endif %}
{% endblock %}

blog/templates/base.html
<!doctype html>
<html lang="en">

    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <title>BLOG App</title>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    </head>

    <body>
        <style>
<!--            body {-->
<!--            font-family: "Roboto", sans-serif;-->
<!--            font-size: 17px;-->
<!--            background-color: #fdfdfd;-->
<!--        }-->
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #1259ff;
            height: auto;
            width: center;
            padding-bottom: 10px;
            box-shadow: 0 16px 48px #dedede;
        }
    </style>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:home' %}"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item ">
                            <a href="{% url 'blog:add_blog' %}" class='btn btn-primary '>Add Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">LOGOUT</a>
                        </li>
                      {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'register' %}">REGISTER</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">LOGIN</a>
                        </li>

                      {% endif %}
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="{% url 'register' %}">REGISTER</a>-->
<!--                        </li>-->
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="{% url 'login' %}">LOGIN</a>-->
<!--                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}" >HOME</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">

        {% block content %}
        <!-- Content Goes here -->

        {% endblock content %}
         </div>
    </body>
</html>

blog/templates/delete_blog.html
{% extends 'base.html' %}
{% block title %} Delete Blog Post {% endblock %}

{% block content %}
    {% if user.is_authenticated %}
    {% if user.id == post.author.id %}

        <br>
        <h1>Delete Post</h1>
        <br>
        <h4>Post Name : {{ post.title }}</h4>
        <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <strong>Are You Sure?</strong><br><br>
            <button class="btn btn-danger" >Delete Post</button>
        </div>
    {% endif %}
    {% endif %}
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
<!--    body {-->
<!--        font-family: "Calibri", Sans-serif;-->
<!--        font-size: 20px;-->
<!--        background-color: white;-->
<!--    }-->

    .head_text {
        color: white;
    }

    .card {
        width: center;
        box-shadow: 0 16px 48px #E3E7EB;
    }

</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-auto mx-auto">
                <div class="site-heading">
                    <h2 class=" site-heading my-auto mt-lg-4 text-white"> WELCOME TO BLOG APPLICATION!</h2>
                    <br>
                    <h6 class="text-center site-heading  mt-lg-auto text-white" >ALL BLOGS 📮</h6>
                    </div>
<!--            <a href="{% url 'blog:add_blog' %}" class='btn btn-primary'>Add Blog</a>-->
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-center mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
<!--                    next four lines are the display for all the posts-->
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Read More...</a>
                   {% if user.is_authenticated %}
                    {% if user.id == post.author.id %}
                    <a href="{% url 'blog:delete_blog' post.slug  %}" class="btn btn-danger">Delete Post</a>
                    {% endif %}
                    {% endif %}

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}

blog/templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-center card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
      </div>
    </div>
</div>
<div class="d-grid gap-2 col-2 mx-auto">
<!--      <div class="d-grid gap-2 col-auto mx-auto">-->
<a href="{% url 'blog:home' %}" class="btn btn-primary">Back</a>
</div>
<br>
{% if user.is_authenticated %}
{% if user.id == post.author.id %}
<div class="d-grid gap-2 col-2 mx-auto">
<a href="{% url 'blog:delete_blog' post.slug %}" class="btn btn-danger">Delete</a>
</div>{% endif %}
{% endif %}

{% endblock content %}