blog/urls.py
from .views import PostList, PostDetail, deleteBlog, addblog
from django.urls import path
# from blog.views import addBlog
app_name = 'blog'
urlpatterns = [
    path('', PostList.as_view(), name='home'),
    path('delete/<str:slug>/', deleteBlog.as_view(), name='delete_blog'),
    path('add/', addblog, name='add_blog'), # I tried to paste this line in the last url, But it showed me a error and after that I pasted this above ...then it runs
    path('<str:slug>/', PostDetail.as_view(), name='post_detail'),
]

polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

tft1/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('home.urls')),
    path('login/', include('django.contrib.auth.urls')), # for login authentication # first django checks this path and then come to the custom urls that we have created
    path('login/', include('login.urls')), # for login authentication
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

# The path() function is passed four arguments, 
# two required: route and view, and two optional: kwargs, and name. At this point, it’s worth reviewing what these arguments are for.


#When to use include()
# You should always use include() when you include other URL patterns. 
# admin.site.urls is the only exception to this.

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    #
    # @admin.display(
    #     boolean=True,
    #     ordering='pub_date',
    #     description='Published recently?',
    # )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    #
    # def was_published_recently(self):
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from re import template
from django.http import HttpResponseRedirect , HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% extends "polls/look.html" %}
{% block content %}

<div class="d-grid gap-2 col-4 mx-auto">
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <br>
        <legend><h2>{{ question.question_text }}</h2></legend>
        <br>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
        {% endfor %}

    </fieldset>
    <br>
    <div class="d-grid gap-2 col-12 mx-auto">
    <button class="btn btn-outline-primary">SELECT</button>
    </div>
    </form>
<div class="d-grid gap-2 col-12 mx-auto">
<a class="btn btn-outline-danger" href="{% url 'home' %}" >EXIT</a>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/look.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<br>
<div class="d-grid gap-2 col-6 mx-auto">

<div class="d-grid gap-auto col-auto mx-auto">
    <h3>Select Question</h3>
            <br>

</div>

{% if latest_question_list %}
    {% for question in latest_question_list %}
<div class="d-grid gap-2 col-6 mx-auto">
        <a href="{% url 'polls:detail' question.id %}" class="btn btn-outline-primary">{{ question.question_text }}</a>
</div>
<br>
        {% endfor %}
{% else %}
    <p>No polls are available. Just create one from Admin panel on something</p>
{% endif %}


<div class="d-grid gap-2 col-2 mx-auto">

<a class="btn btn-outline-danger" href="{% url 'home' %}" >EXIT</a>
</div>

{% endblock %}


<!-- 
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->

polls/templates/polls/look.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Polls App!</title>
  </head>
  <body>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

<!--    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>-->

          <div class="container">

        {% block content %}

        {% endblock content %}
         </div>
  </body>
</html>

polls/templates/polls/results.html
{% extends "polls/look.html" %}
{% block content %}
<div class="d-grid gap-2 col-4 mx-auto">
<br>
  <h2>RESULT</h2>
{% for choice in question.choice_set.all %}
    <a>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</a>

{% endfor %}

<br>
<a href="{% url 'polls:detail' question.id %}" class="btn btn-outline-primary">Vote again?</a>
<a class="btn btn-outline-primary" href="{% url 'polls:index' %}" >Select Different Question.</a>
<a class="btn btn-outline-danger" href="{% url 'home' %}" >EXIT</a>

</div>


{% endblock %}